version: '3.1'

services:

  front:
    build:
      context: .
      dockerfile: frontend
      args:
        MYSQL_DATABASE: php_mysql_crud
        MYSQL_DEFAULT_USER: root
        MYSQL_ROOT_PASSWORD: password123
    restart: always
    ports:
      - 90:90
    networks:
       back:
         ipv4_address: 10.15.1.15
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: php_mysql_crud
      MYSQL_DEFAULT_USER: root
      MYSQL_ROOT_PASSWORD: password123
            
    volumes:
      - db:/var/lib/mysql
    networks:
       back:
         ipv4_address: 10.15.1.16

volumes:
  db:
networks:
  back:
    driver: bridge
    ipam:
     config:
       - subnet: 10.15.1.0/16
         gateway: 10.15.1.1
       
         
    
